name: Update Dependency Graph
on:
  push:
    branches: [master]
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2
