name: Update Dependency Graph
on:
  push:
    branches: [master]
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - uses: advanced-security/maven-dependency-submission-action@v4
