name: Release
on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Sonatype key
        run: |
          mkdir -p /tmp/gpg
          chmod 700 /tmp/gpg
          export GNUPGHOME=/tmp/gpg
          gpg --batch --yes --decrypt --passphrase "${{ secrets.SONATYPE_KEY_PASSWORD }}" sonatype.key.gpg | gpg --batch --yes --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<-EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>ossrh</id>
                <username>${{ secrets.SONATYPE_ORG_USER }}</username>
                <password>${{ secrets.SONATYPE_ORG_PASSWORD }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>ossrh</id>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>
                <properties>
                  <gpg.keyname>${{ secrets.SONATYPE_KEY_ID }}</gpg.keyname>
                  <gpg.passphraseServerId>ossrh</gpg.passphraseServerId>
                </properties>
              </profile>
            </profiles>
          </settings>
          EOF

      - name: Run tests and publish to Maven Central
        run: |
          export GNUPGHOME=/tmp/gpg
          export SOURCE_DATE_EPOCH=$(date +%s)
          make test
          
          # Check if this is a release version (non-SNAPSHOT)
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version: $PROJECT_VERSION"
          
          if [[ "$PROJECT_VERSION" == *"-SNAPSHOT" ]]; then
            echo "Snapshot version detected, deploying to snapshots repository"
            mvn deploy -q
          else
            echo "Release version detected, deploying to Maven Central with release profile"
            mvn deploy -Prelease -DskipTests -Dgpg.passphrase=""
          fi